version: '3.8'
services:
  # 1. ZOOKEEPER (Kafka'nın beyni)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # 2. KAFKA (Mesaj Kuyruğu)
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      # Dışarıdan (IDE) erişim için 9092, İçeriden (Docker) erişim için 29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  # 3. REDIS (Rate Limiting için)
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  # 4. ZIPKIN (Trace İzleme için)
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  # 5. UYGULAMA (Resilient Stock Service)
  app:
    build: .  # Dockerfile'ı burada ara ve build et
    container_name: stock-service
    ports:
      - "8080:8080" # Dışarıya 8080 portunu aç
    depends_on:
      - kafka
      - redis
      - zipkin
    environment:
      # Application.yml ayarlarını buradan EZİYORUZ (Override)
      # Artık localhost yok, servis isimleri var!
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_DATA_REDIS_HOST: redis
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    restart: on-failure # Eğer Kafka henüz hazır değilse ve app çökerse tekrar dene